#!/usr/bin/env bash
set -euo pipefail

ARCHIVE=""
REMOTE=""
REMOTE_ROOT="/opt/sism-releases"
TARGET_DIR="/opt/sism-stack/production"
ENV_FILE=""
UPLOAD_ONLY=false

usage() {
  cat <<'EOF'
Usage: upload-offline-release.sh --archive FILE --remote USER@HOST [options]

Options:
  --archive FILE      Offline release .tar.gz generated by download script
  --remote USER@HOST  SSH destination
  --remote-root DIR   Remote release archive directory
  --target DIR        Remote Compose stack directory
  --env-file FILE     Optional local production .env to install remotely
  --upload-only       Upload and verify without deploying
  -h, --help          Show this help
EOF
}

log() {
  printf '[offline-upload] %s\n' "$1"
}

fail() {
  printf '[offline-upload] ERROR: %s\n' "$1" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --archive)
      ARCHIVE="$2"
      shift 2
      ;;
    --remote)
      REMOTE="$2"
      shift 2
      ;;
    --remote-root)
      REMOTE_ROOT="$2"
      shift 2
      ;;
    --target)
      TARGET_DIR="$2"
      shift 2
      ;;
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --upload-only)
      UPLOAD_ONLY=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

[[ -n "${ARCHIVE}" ]] || fail "--archive is required"
[[ -n "${REMOTE}" ]] || fail "--remote is required"
[[ -f "${ARCHIVE}" ]] || fail "Archive does not exist: ${ARCHIVE}"
[[ "${ARCHIVE}" == *.tar.gz ]] || fail "Archive must end with .tar.gz"
[[ "${REMOTE_ROOT}" =~ ^/[A-Za-z0-9._/-]+$ ]] || fail "Invalid remote root"
[[ "${TARGET_DIR}" =~ ^/[A-Za-z0-9._/-]+$ ]] || fail "Invalid target directory"
if [[ -n "${ENV_FILE}" ]]; then
  [[ -f "${ENV_FILE}" ]] || fail "Environment file does not exist: ${ENV_FILE}"
fi
for command_name in scp ssh tar; do
  command -v "${command_name}" >/dev/null 2>&1 || fail "Missing required command: ${command_name}"
done

ARCHIVE="$(cd "$(dirname "${ARCHIVE}")" && pwd)/$(basename "${ARCHIVE}")"
ARCHIVE_NAME="$(basename "${ARCHIVE}")"
RELEASE_NAME="${ARCHIVE_NAME%.tar.gz}"
CHECKSUM_FILE="${ARCHIVE}.sha256"
[[ -f "${CHECKSUM_FILE}" ]] || fail "Checksum file is missing: ${CHECKSUM_FILE}"

log "Uploading ${ARCHIVE_NAME} to ${REMOTE}:${REMOTE_ROOT}"
ssh "${REMOTE}" bash -s -- "${REMOTE_ROOT}" <<'REMOTE_MKDIR'
set -euo pipefail
mkdir -p "$1"
REMOTE_MKDIR
scp "${ARCHIVE}" "${CHECKSUM_FILE}" "${REMOTE}:${REMOTE_ROOT}/"

REMOTE_ENV=""
if [[ -n "${ENV_FILE}" ]]; then
  REMOTE_ENV="${REMOTE_ROOT}/${RELEASE_NAME}.production.env"
  scp "${ENV_FILE}" "${REMOTE}:${REMOTE_ENV}"
  ssh "${REMOTE}" bash -s -- "${REMOTE_ENV}" <<'REMOTE_CHMOD'
set -euo pipefail
chmod 600 "$1"
REMOTE_CHMOD
fi

ssh "${REMOTE}" bash -s -- "${REMOTE_ROOT}" "${ARCHIVE_NAME}" "${RELEASE_NAME}" <<'REMOTE_SCRIPT'
set -euo pipefail
REMOTE_ROOT="$1"
ARCHIVE_NAME="$2"
RELEASE_NAME="$3"
cd "${REMOTE_ROOT}"
if command -v sha256sum >/dev/null 2>&1; then
  sha256sum -c "${ARCHIVE_NAME}.sha256"
else
  shasum -a 256 -c "${ARCHIVE_NAME}.sha256"
fi
rm -rf "${RELEASE_NAME}"
tar -xzf "${ARCHIVE_NAME}"
bash "${RELEASE_NAME}/scripts/install-offline-release.sh" --verify-only
REMOTE_SCRIPT

if [[ "${UPLOAD_ONLY}" == "true" ]]; then
  log "UPLOAD_VERIFIED=${REMOTE}:${REMOTE_ROOT}/${ARCHIVE_NAME}"
  exit 0
fi

ssh "${REMOTE}" bash -s -- "${REMOTE_ROOT}" "${RELEASE_NAME}" "${TARGET_DIR}" "${REMOTE_ENV}" <<'REMOTE_DEPLOY'
set -euo pipefail
REMOTE_ROOT="$1"
RELEASE_NAME="$2"
TARGET_DIR="$3"
REMOTE_ENV="${4:-}"
COMMAND=(bash "${REMOTE_ROOT}/${RELEASE_NAME}/scripts/install-offline-release.sh" --target "${TARGET_DIR}")
if [[ -n "${REMOTE_ENV}" ]]; then
  COMMAND+=(--env-file "${REMOTE_ENV}")
fi
"${COMMAND[@]}"
REMOTE_DEPLOY
log "REMOTE_DEPLOY_SUCCESS=${REMOTE}:${TARGET_DIR}"
